[project]
name = "agentic-ai-using-langgraph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.13"
dependencies = [
    "langgraph>=1.0.1",
    "notebook>=7.4.7",
    "python-dotenv>=1.1.1",
]
